# LOADING DATASET

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


iris = load_iris()

x = iris.data
y = iris.target

feature_names = iris.feature_names
target_names = iris.target_names


print("Features names - ", feature_names)
print("target name - ", target_names)

print("\n Type of X is :", type(x))
print("\n type of Y is :", type(y))


print("\nFirst 5 rows of X :\n", x[:5])

Features names -  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target name -  ['setosa' 'versicolor' 'virginica']

 Type of X is : <class 'numpy.ndarray'>

 type of Y is : <class 'numpy.ndarray'>

First 5 rows of X :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


# SPLITING DATASET

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state = 1)

In [3]:
print("x_train shape - ", x_train.shape)
print("x_test shape - ", x_test.shape)
print("y_train shape - ", y_train.shape)
print("y_test shape - ", y_test.shape)

x_train shape -  (90, 4)
x_test shape -  (60, 4)
y_train shape -  (90,)
y_test shape -  (60,)


# HANDLING CATEGORICAL DATASET

# 1.LABEL ENCODING

In [4]:
# LabelEncoder() -> encoder object that convert categorical object into numerical labels.
# fit_transform() -> firstly fits the categorical data and then convert into corresponding numerical labels.

In [5]:
from sklearn.preprocessing import LabelEncoder

categorical_feature  = ["cat", "dog", "dog", "cat", "bird"]

encoder = LabelEncoder()

encoded_feature = encoder.fit_transform(categorical_feature)

print("Encoded feature :", encoded_feature)

Encoded feature : [1 2 2 1 0]


# 2.ONE HOT ENCODING

In [8]:
from sklearn.preprocessing import OneHotEncoder

categorical_feature = ['cat', "dog", 'dog', 'cat', "bird"]

categorical_feature = np.array(categorical_feature).reshape(-1,1)

encoder = OneHotEncoder(sparse_output = False)

encoded_feature = encoder.fit_transform(categorical_feature)

print("OneHotEncoded Feature: \n", encoded_feature)

OneHotEncoded Feature: 
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


# TRAINING THE MODEL

In [9]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter = 200)

log_reg.fit(x_train, y_train)

LogisticRegression(max_iter=200)

# MAKE PREDICTIONS

In [10]:
y_pred = log_reg.predict(x_test)

# EVALUATING MODEL ACCURACY

In [11]:
from sklearn import metrics

print("Logistic Regression model accuracy:", metrics.accuracy_score(y_test, y_pred))

Logistic Regression model accuracy: 0.9666666666666667


In [21]:
sample = [[3,5,4,2],[2,3,5,4]]

preds = log_reg.predict(sample)

print(preds)
# pred_species = [iris.target_names[p] for p in preds]

# print("Predictions - ", pred_species)

[2 2]
